version: 0.0
os: linux
files:
  - source: code_output_demo_app
    destination: /var/www/html/
hooks:
  AfterInstall:
    - location: scripts/install_nginx.sh
      timeout: 300
      runas: root
  ApplicationStart:
  - location: scripts/start_nginx.sh
    timeout: 300
    runas: root